### ISSUE TITLE
ABRT section needs expansion

### ISSUE THREAD

**Issue by bexelbie** [lukaskotek/fedora-handbook-doc#14]
Today we have:

> There is a also a tool in Fedora called ABRT. ABRT can be described by quotation from a classic movie - "everybody contributes accordingly to hi  s possibilities".

This doesn't describe ABRT.  Also, I don't recognize this quote which makes me wonder where it came from.  Either way, the quote doesn't actually help anyone understand ABRT.

**Comment by ghost** [comment]
Thank you for notice. I couldn't believe it's really there... and it is! The goal was to emphasize something like "you can help Fedora as you want to, at least you can send automatic bug report" ... But you're right it's not good (and looks really strange translated to english). 

Now it seems like definition of socialism, which definitely wasn't intention of mine. The origin of the quote is from the czech dubbed version of Starship troopers (to be more specific -- one of the propaganda videos):  "everyone is doing their part". I paraphrased it and here we are... It probably sounds a bit crazy now ;-)

I marvel nobody noticed in czech version. I'll remove it for the next version of handbook. Also feel free to change the paragraph in present english version.

**Comment by bexelbie** [comment]
I've updated the paragraph ... I am sure it still needs work.  I should watch Starship Troopers some day

**Comment by bexelbie** [comment]
Just noticed my changes for 06 got merged ... submitting a new PR
